steps:
- id: buildArtifact
  waitFor: ["-"]
  name: gcr.io/cloud-builders/docker
  args: ["build", "-t", "artifact", "-f", "Dockerfile.artifact", "."]
- id: buildAlpineImage
  waitFor: ["buildArtifact"]
  name: gcr.io/cloud-builders/docker
  args: ["build", "-t", "gcr.io/$PROJECT_ID/gate:$TAG_NAME-alpine", "-f", "Dockerfile.alpine", "."]
- id: buildUbuntuImage
  waitFor: ["buildArtifact"]
  name: gcr.io/cloud-builders/docker
  args: ["build", "-t", "gcr.io/$PROJECT_ID/gate:$TAG_NAME-ubuntu", "-f", "Dockerfile.ubuntu", "."]
- id: tagDefaultImage
  waitFor: ["buildAlpineImage"]
  name: gcr.io/cloud-builders/docker
  args: ["tag", "gcr.io/$PROJECT_ID/gate:$TAG_NAME-alpine", "gcr.io/$PROJECT_ID/gate:$TAG_NAME"]
images:
- gcr.io/$PROJECT_ID/gate:$TAG_NAME-alpine
- gcr.io/$PROJECT_ID/gate:$TAG_NAME-ubuntu
- gcr.io/$PROJECT_ID/gate:$TAG_NAME
timeout: 3600s
options:
  machineType: N1_HIGHCPU_8
