steps:
- name: gcr.io/cloud-builders/docker
  args: ["build", "-t", "gcr.io/$PROJECT_ID/$REPO_NAME:$TAG_NAME", "-f", "Dockerfile", "."]
images:
- gcr.io/$PROJECT_ID/$REPO_NAME:$TAG_NAME
timeout: 3600s
options:
  machineType: N1_HIGHCPU_8
